### PR TITLE
fix GdipImageSearch for x64

### PR DESCRIPTION
**Pull request by mmikeww**
see this thread where XXaXXion finds the bug:  
https://autohotkey.com/boards/viewtopic.php?f=5&t=26255

### CODE REVIEW

**Comment by mmikeww** [comment]
bump?

**Comment by MasterFocus** [comment]
@mmikeww Sorry for the very late response and thanks for the PR!

**Comment by just43go** [comment]
script is not working properly when boundaries are set. 
For example,
RET := Gdip_ImageSearch(bmpHaystack,bmpNeedle, OutputList, x1, y1, x2, y2)

Let's say the pix locates at (20, 50), 
when x1 set to 21, we can still find the pix, 
or when x1 is set to 0, and x2 set to 15 we can still find the pix.

**Comment by mmikeww** [comment]
> script is not working properly when boundaries are set.

It should. Please post both haystack and needle images and example script showing the problem.

**Comment by just43go** [comment]
`
#NoEnv  ; Recommended for performance and compatibility with future AutoHotkey releases.
#Warn All, Off    ; #Warn eables warnings to assist with detecting common errors, while "all, off" makes them all disabled
#HotkeyInterval 1000  ; This is  the default value (milliseconds).
#MaxHotkeysPerInterval 200
#MaxThreadsPerHotkey 1
#SingleInstance
SetWorkingDir %A_ScriptDir%  ; Ensures a consistent starting directory.

#Include Gdip_All.ahk    
#Include Gdip_imagesearch.ahk  

If !pToken := Gdip_Startup()                        
{
   MsgBox, 48, gdiplus error!, Gdiplus failed to start. Please ensure you have gdiplus on your system
   ExitApp
}

F1::
	imagesearch2("crit",25,0,100,0,*0)
	return




imagesearch2(ini,mx1,my1,mx2,my2,v1)
{
	WinGet, active_id, ID, A
	dirc = P:\Program Files\AutoHotkey\script\game\%ini%.png
	bmpNeedle := Gdip_CreateBitmapFromFile(dirc)
	bmpArea := Gdip_BitmapFromHWND(active_id)
	RET := Gdip_ImageSearch(bmpArea,bmpNeedle, OutputList,%mx1%,%my1%,%mx2%,%my2%,%v1%)		
	Gdip_DisposeImage(bmpNeedle)
	Gdip_DisposeImage(bmpArea)
	Msgbox,,Test board,RET: %RET%,`nOutputList: %OutputList%
}
`


here are my scripts, please take a look. 
I am really noob to ahk, so please let me know how to fix it.

**Comment by mmikeww** [comment]
> here are my scripts, please take a look.

You didn't post the actual image files, so its impossible to confirm if there is a bug or not. 
However, from a quick look at your code, this line is definitely wrong:
`RET := Gdip_ImageSearch(bmpArea,bmpNeedle, OutputList,%mx1%,%my1%,%mx2%,%my2%,%v1%)`
You should not be using %%'s around those variables inside the function call expression
Also, you should not be putting an asterisk in front of the variation parameter, you only do that if you were using AHKs built-in ImageSearch command:
`imagesearch2("crit",25,0,100,0,*0)`

> I am really noob to ahk, so please let me know how to fix it.

Then you really should be posting in the AHK forums under Ask For Help:
https://www.autohotkey.com/boards/
Github is for issues directly related to this function. Please post further questions on the AHK forums

**Pull request merged**
